version: '3.8'

services:
  backend:
    build:
      context: ./Disease_predictor_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: >
      sh -c "apt-get update && apt-get install -y libgl1-mesa-glx &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app-network
    environment:
      - CORS_ORIGINS=http://localhost:5173

  frontend:
    build:
      context: ./Studio_main
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    command: >
      sh -c "./wait-for.sh backend:8000 -- npm run dev -- --host 0.0.0.0"
    volumes:
      - ./Studio_main/.env:/app/.env
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=http://localhost:8000  # Changed to localhost

networks:
  app-network:
    driver: bridge